hmcts/chart-job

- README.md
- job/Chart.yaml
- job/templates/CronJob.yaml
- job/templates/Job.yaml
- job/values.yaml
Changing kind to global value to be able to manage in child charts and enforce rules from Jenkins
```
[ ] Yes
[x] No
```
> Changing kind to global value to be able to manage in child charts

- README.md
- job/Chart.yaml
- job/templates/CronJob.yaml
Added some missing optional fields for cronjob to be able to suspend cronjobs when not to be used .
```
[ ] Yes
[x] No
```
> Added some missing optional fields for cronjob

- README.md
- azure-pipelines.yml
- ci-values.yaml
- job/templates/_helpers.tpl
- job/templates/_jobspec.tpl
Add ability to add labels to job spec
```
[ ] Yes
[x] No
```
> Add ability to add labels to job spec

- job/Chart.yaml
Bumping chart version
```
[ ] Yes
[x] No
```
> Bumping chart version

- job/Chart.yaml
- job/templates/CronJob.yaml
Fixing suspend to boolean
```
[ ] Yes
[x] No
```
> Fixing suspend flag to boolean

- README.md
- job/Chart.yaml
- job/templates/_jobspec.tpl
Adding option to enable pod identity
```
[ ] Yes
[x] No
```
> Adding option to enable pod identity

- README.md
- ci-values.yaml
- job/Chart.yaml
- job/templates/_jobspec.tpl
- job/values.yaml
changes to toggle keyvaults
```
[ ] Yes
[x] No
```
> changes to toggle keyvaults

- job/Chart.yaml
- job/templates/_jobspec.tpl
- job/values.yaml
Related to: [[AB#322](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/322)]
```
[ ] Yes
[x] No
```
> Add restartPolicy variable

- README.md
- ci-values.yaml
- job/Chart.yaml
- job/templates/_jobspec.tpl
> removing subscriptionid and rg for keyvaults

- README.md
- ci-values.yaml
- job/Chart.yaml
- job/templates/CronJob.yaml
- job/templates/Job.yaml
- job/values.yaml
[[AB#590](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/590)]
```
[ ] Yes
[x] No
```
> Local kind evaluates before global if it exists

- Makefile
- README.md
- job/Chart.yaml
- job/templates/CronJob.yaml
- job/templates/Job.yaml
- job/values.yaml
> Clean up global override

- ci-values.yaml
- job/Chart.yaml
- job/templates/CronJob.yaml
> Changing startingDeadlineSeconds  to int as k8s complains

- README.md
- ci-values.yaml
- job/Chart.yaml
- job/templates/_jobspec.tpl
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Added Args support

- README.md
- ci-values.yaml
- job/Chart.yaml
- job/templates/_jobspec.tpl
Include args for running small jobs
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> adding args support

- job/Chart.lock
- job/Chart.yaml
- job/templates/CronJob.yaml
- job/templates/Job.yaml
- job/templates/_jobspec.tpl
- job/values.yaml
> Upgrade library

- job/Chart.yaml
Fix for warning related to pipeline run for PR-767 in cnp-jenkins-library - https://hmcts-reform.slack.com/archives/C01HP1ZL4R5/p1627898124018800
> Update chart library to v0.6.1

- azure-pipelines.yml
[DTSPO-8339](https://tools.hmcts.net/jira/browse/DTSPO-8339)
```
[ ] Yes
[x] No
```
> Parameterize ADO vmImage

- job/Chart.yaml
Upgrading chart-library - needing to use args from library chart
```
[ ] Yes
[ x] No
```
> Upgrade chart library for args

- .gitignore
- job/Chart.lock
- job/Chart.yaml
- job/templates/CronJob.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Dtspo-12023   update api version

- job/Chart.yaml
- job/templates/CronJob.yaml
- job/values.yaml
[DTSPO-15287](https://tools.hmcts.net/jira/browse/DTSPO-15287)
adding options so cronjob template can target a specific node.
> DTSPO-15287 adding nodeSelector and tolerations to chart-job

- job/templates/Job.yaml
[DTSPO-15292](https://tools.hmcts.net/jira/browse/DTSPO-15292)
> DTSPO-15292 adding condition to job template

- job/Chart.yaml
[DTSPO-15293](https://tools.hmcts.net/jira/browse/DTSPO-15293)
> DTSPO-15293-updating-to-latest-chart-library-version

- job/Chart.yaml
- job/templates/_jobspec.tpl
https://tools.hmcts.net/jira/browse/DTSPO-17826
Updating chart-library dependency
> Updating chart-library dependency

- job/Chart.yaml
https://tools.hmcts.net/jira/browse/S28-3685
> Move Base chart to OCI
